homework_09/sales_shop/sales_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html") ,name= "index"),
    # path('/', admin.site.urls),
    path("shop/", include("shop.urls")),
    path("auth/", include("site_auth.urls")),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

homework_09/sales_shop/shop/urls.py
from django.urls import path
from .views import (
    ShopIndexView,
    CategoriesWithProductsTree,
    ProductsView,
    OrdersListView,
    CategoriesListView,
    CategoryCreateView,
    CategoryDetailView,
    CategoryUpdateView,
    CategoryDeleteView,
    ProductDetailView,
    HelloView,
    get_task_info,
)

app_name = "shop"

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("products/", ProductsView.as_view(), name="products"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("products/<int:pk>", ProductDetailView.as_view(), name="product"),
    path("categories/", CategoriesListView.as_view(), name="categories"),
    path("categories/create/", CategoryCreateView.as_view(), name="create-category"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="update-category"),
    path("categories/<int:pk>/confirm-delete/", CategoryDeleteView.as_view(), name="confirm-delete-category"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category"),
    path("orders/", OrdersListView.as_view(), name="orders"),
    path("orders/task/<task_id>/", get_task_info, name="get-order-task"),
    path(
        "categories-as-tree/",
        CategoriesWithProductsTree.as_view(),
        name="categories_with_products_tree",
    ),
]

homework_09/sales_shop/site_auth/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import LogonView,LogoutView,RegisterView


app_name = "site_auth"

urlpatterns = [
    path(
        "me/",
        TemplateView.as_view(template_name="site_auth/me.html"),
        name="about-me",
    ),
    path(
        "login/",
        # TemplateView.as_view(template_name="site_auth/login.html"),
        LogonView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
]

homework_09/sales_shop/site_auth/models.py
from django.db import models

# Create your models here.

homework_09/sales_shop/site_auth/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm as AuthenticationFormGeneric,
    UserCreationForm as UserCreationFormGeneric,
)


class AuthenticationForm(AuthenticationFormGeneric):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"


class UserCreationForm(UserCreationFormGeneric):
    class Meta(UserCreationFormGeneric.Meta):
        fields ="username", "email"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"

homework_09/sales_shop/site_auth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.views import LoginView as LoginViewGeneric
from django.contrib.auth.views import LogoutView as LogoutViewGeneric
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .tasks import welcome_new_user
from .forms import AuthenticationForm, UserCreationForm


class LogonView(LoginViewGeneric):
    template_name = "site_auth/login.html"
    form_class = AuthenticationForm
    next_page = reverse_lazy("site_auth:about-me")


class LogoutView(LogoutViewGeneric):
    next_page = reverse_lazy("site_auth:about-me")


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "site_auth/register.html"
    success_url = reverse_lazy("site_auth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        # user: AbstractUser =self.object
        welcome_new_user.delay(self.object.pk)

        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password1")

        user:AbstractUser= authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response
    

homework_09/sales_shop/site_auth/templates/site_auth/login.html
{% extends 'base.html' %}

{% block title %}
Login to site
{% endblock title %}

{% block body %}

<!-- Pills content -->
<div class="tab-content">
    <div class="tab-pane fade show active" id="pills-login" role="tabpanel"
        aria-labelledby="tab-login">
        <form method="post">
            {% csrf_token %}
            {% if form.errors%}
            <p class="alert alert-danger">
                Something error
            </p>
            {% endif %}
            {{form.as_p}}
            
            <input type="hidden" name="text" value ="{{next}}">
            <!-- 2 column grid layout -->

            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

            <!-- Register buttons -->
            <div class="text-center">
                <p>Not a member? <a href="{% url 'site_auth:register' %}">Register</a></p>
            </div>
        </form>
    </div>
    <div class="tab-pane fade" id="pills-register" role="tabpanel"
        aria-labelledby="tab-register">
        <form>

            <!-- Name input -->
            <div class="form-outline mb-4">
                <input type="text" id="registerName" class="form-control" />
                <label class="form-label" for="registerName">Name</label>
            </div>

            <!-- Username input -->
            <div class="form-outline mb-4">
                <input type="text" id="registerUsername" class="form-control" />
                <label class="form-label" for="registerUsername">Username</label>
            </div>

            <!-- Email input -->
            <div class="form-outline mb-4">
                <input type="email" id="registerEmail" class="form-control" />
                <label class="form-label" for="registerEmail">Email</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
                <input type="password" id="registerPassword"
                    class="form-control" />
                <label class="form-label" for="registerPassword">Password</label>
            </div>

            <!-- Repeat Password input -->
            <div class="form-outline mb-4">
                <input type="password" id="registerRepeatPassword"
                    class="form-control" />
                <label class="form-label" for="registerRepeatPassword">Repeat
                    password</label>
            </div>

            <!-- Checkbox -->
            <div class="form-check d-flex justify-content-center mb-4">
                <input class="form-check-input me-2" type="checkbox" value
                    id="registerCheck" checked
                    aria-describedby="registerCheckHelpText" />
                <label class="form-check-label" for="registerCheck">
                    I have read and agree to the terms
                </label>
            </div>

            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-3">Sign in</button>
        </form>
    </div>
</div>
<!-- Pills content -->
{% endblock %}

homework_09/sales_shop/site_auth/templates/site_auth/me.html
{% extends 'base.html' %}

{% block title %}
    About me
{% endblock %}


{% block body %}
    <h1>User info</h1>
    {% if user.is_authenticated %}
        <p>Username:{{user.username}}</p>
        <p>email:{{user.email}}</p>
        {% else %}
        <h2> Anonymous user </h2>
    {% endif %}
{% endblock body %}
    

homework_09/sales_shop/site_auth/templates/site_auth/register.html
{% extends 'base.html' %}


{% block title %}
    Register
{% endblock title %}
    


{% block body %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" value="Register">
    </form>
{% endblock body %}
    