homework_09/sales_shop/sales_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html") ,name= "index"),
    # path('/', admin.site.urls),
    path("shop/", include("shop.urls")),
    path("auth/", include("site_auth.urls")),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

homework_09/sales_shop/shop/urls.py
from django.urls import path
from .views import (
    ShopIndexView,
    CategoriesWithProductsTree,
    ProductsView,
    OrdersListView,
    CategoriesListView,
    CategoryCreateView,
    CategoryDetailView,
    CategoryUpdateView,
    CategoryDeleteView,
    ProductDetailView,
    HelloView,
    get_task_info,
)

app_name = "shop"

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("products/", ProductsView.as_view(), name="products"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("products/<int:pk>", ProductDetailView.as_view(), name="product"),
    path("categories/", CategoriesListView.as_view(), name="categories"),
    path("categories/create/", CategoryCreateView.as_view(), name="create-category"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="update-category"),
    path("categories/<int:pk>/confirm-delete/", CategoryDeleteView.as_view(), name="confirm-delete-category"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category"),
    path("orders/", OrdersListView.as_view(), name="orders"),
    path("orders/task/<task_id>/", get_task_info, name="get-order-task"),
    path(
        "categories-as-tree/",
        CategoriesWithProductsTree.as_view(),
        name="categories_with_products_tree",
    ),
]

homework_09/sales_shop/site_auth/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import LogonView,LogoutView,RegisterView


app_name = "site_auth"

urlpatterns = [
    path(
        "me/",
        TemplateView.as_view(template_name="site_auth/me.html"),
        name="about-me",
    ),
    path(
        "login/",
        # TemplateView.as_view(template_name="site_auth/login.html"),
        LogonView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
]

homework_09/sales_shop/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
            crossorigin="anonymous">
        <title>{% block title %}

            {% endblock %}</title>
    </head>
    <body class="bg-light-subtle">
        <nav class=" px-2 navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'index' %}">Shop</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav mr-auto">
                    </ul>
                </div>
            </div>
            <ul class="navbar-nav">

                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'site_auth:about-me' %}">{{user.username}}</a>
                <a class="nav-link" href="{% url 'site_auth:logout' %}">Logout</a>
                {% else %}
                <a class="nav-link mx-5" href="{% url 'site_auth:login' %}">Login</a>

                {% endif %}

            </ul>
        </nav>
        <div class="container">
            {% block body %}

            {% endblock %}
        </div>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    </body>
</html>

homework_09/sales_shop/templates/index.html
{% extends 'base.html' %}


{% block title %}
    Sales shop index
{% endblock title %}
    

{% block body %}
    <h1>Hello</h1>

    <div>
        <p>
            Links:
        </p>
        <ul>
            <li>
                <a href="{% url 'shop:index'%}">Shop index</a>
            </li>
        </ul>
    </div>
{% endblock body %}
    