homework_09/sales_shop/sales_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html") ,name= "index"),
    # path('/', admin.site.urls),
    path("shop/", include("shop.urls")),
    path("auth/", include("site_auth.urls")),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

homework_09/sales_shop/shop/urls.py
from django.urls import path
from .views import (
    ShopIndexView,
    CategoriesWithProductsTree,
    ProductsView,
    OrdersListView,
    CategoriesListView,
    CategoryCreateView,
    CategoryDetailView,
    CategoryUpdateView,
    CategoryDeleteView,
    ProductDetailView,
    HelloView,
    get_task_info,
)

app_name = "shop"

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("products/", ProductsView.as_view(), name="products"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("products/<int:pk>", ProductDetailView.as_view(), name="product"),
    path("categories/", CategoriesListView.as_view(), name="categories"),
    path("categories/create/", CategoryCreateView.as_view(), name="create-category"),
    path("categories/<int:pk>/update/", CategoryUpdateView.as_view(), name="update-category"),
    path("categories/<int:pk>/confirm-delete/", CategoryDeleteView.as_view(), name="confirm-delete-category"),
    path("categories/<int:pk>/", CategoryDetailView.as_view(), name="category"),
    path("orders/", OrdersListView.as_view(), name="orders"),
    path("orders/task/<task_id>/", get_task_info, name="get-order-task"),
    path(
        "categories-as-tree/",
        CategoriesWithProductsTree.as_view(),
        name="categories_with_products_tree",
    ),
]

homework_09/sales_shop/shop/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

from .tasks import notify_order_saved


class Category(models.Model):
    class Meta:
        # verbose_name = "Category"
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=20, unique=True)
    description = models.CharField(max_length=200)
    archived = models.BooleanField(default=False)
    
    def get_absolute_url(self) -> str:
        return reverse("shop:category", kwargs={"pk": self.pk})    
    
    def __str__(self):
        return self.name


class Product(models.Model):
    class Status(models.IntegerChoices):
        ARCHIVED = 0
        AVAILABLE = 1

    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, related_name="products"
    )
    status = models.IntegerField(choices=Status.choices)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Product <{self.pk}, {self.name!r}>"


class Order(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.PROTECT)
    products = models.ManyToManyField(
        Product,
        related_name="orders",
    )
    adress = models.TextField()
    promocode = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


class OrderPaymentDeteils(models.Model):
    class Meta:
        verbose_name_plural = "Order Payment Details"

    class Status(models.IntegerChoices):
        PENDING = 0
        CONFIRMED = 1

    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name="payment_details"
    )
    payed_at = models.DateTimeField(blank=True, null=True)
    card_ends_with = models.CharField(max_length=5, blank=True)
    status = models.IntegerField(choices=Status.choices, default=Status.PENDING)


@receiver(post_save, sender=Order)
def on_order_save(instance: Order, created: bool, **kw):
    task =notify_order_saved.delay(
        order_pk=instance.pk,
        promocode=instance.promocode,
    )
    print("order new task", task , task.id)
    if not created:
        return
    OrderPaymentDeteils.objects.get_or_create(order=instance)

homework_09/sales_shop/shop/forms.py
from django import forms
from django.forms import Widget

from .models import Category

# class CategoryForm(forms.Form):
#     name = forms.CharField(max_length=100 )
#     description = forms.TextInput(...)


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "name", "description"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name,field in self.fields.items():
            field: forms.Field
            widget: Widget = field.widget
            widget.attrs["class"] = "form-control"
            if isinstance(field,forms.CharField):
                field.widget

homework_09/sales_shop/shop/views.py
from typing import Any, Dict, Optional

from celery.result import AsyncResult
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
    UserPassesTestMixin,
)
from django.db.models import Q
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)

from .forms import CategoryForm
from .models import Category, Order, Product
from .tasks import notify_order_saved


class HelloView(View):
    def get(self,request: HttpRequest)->HttpResponse:
        return HttpResponse("<h1>Hello View</h1>")

class CategoriesListView(ListView):
    # model = Category
    queryset = Category.objects.filter(~Q(archived=True)).all()


class CategoryDetailView(DetailView):
    model = Category


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    # fields = "name" , "description"
    # success_url = reverse
    success_url = reverse_lazy("shop:categories")


class CategoryUpdateView(UpdateView):
    # template_name = ...
    template_name_suffix = "_update_form"
    model = Category
    form_class = CategoryForm
    # success_url =reverse_lazy("shop:category",{})
    # slug_url_kwarg = ""
    # field = "description"

    def get_success_url(self) -> str:
        return reverse("shop:category", kwargs={"pk": self.object.pk})


class CategoryDeleteView(PermissionRequiredMixin,DeleteView):
    permission_required ="shop.delete_category"
    # model = Category
    success_url = reverse_lazy("shop:categories")
    queryset = Category.objects.filter(~Q(archived=True)).all()

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        # return HttpResponseRedirect(success_url)
        return redirect(success_url)


class ShopIndexView(TemplateView):
    template_name = "shop/index.html"


class ProductsView(ListView):
    template_name = "shop/products.html"
    queryset = (
        Product.objects.filter(~Q(status=Product.Status.ARCHIVED))
        .order_by("id")
        .select_related("category")
        .defer(
            "description",
            "created_at",
            "update_at",
            "category__description",
        )
        .all()
    )
    context_object_name = "products"


class ProductDetailView(DetailView):
    model = Product


class OrdersListView(UserPassesTestMixin,ListView):
    def test_func(self) :
        return self.request.user.is_staff
    template_name = "shop/orders.html"
    context_object_name = "orders"
    queryset = (
        Order.objects.order_by("id")
        .select_related("user", "payment_details")
        .prefetch_related("products")
        .all()
    )


class CategoriesWithProductsTree(LoginRequiredMixin, TemplateView):
    template_name = "shop/categories_with_products_tree.html"

    extra_context = {
        "categories": Category.objects.order_by("id").prefetch_related("products").all()
    }
    # def get_context_data(self, **kwargs: Any):
    #     context = super().get_context_data(**kwargs)
    #     categories = Category.objects.order_by("id").prefetch_related("products").all()
    #     context.update(categories=categories)
    #     return context


@login_required
def get_task_info(request: HttpRequest, task_id: str) -> HttpResponse:
    task_result: AsyncResult = notify_order_saved.AsyncResult(task_id)
    return JsonResponse(
        {
            "task_id": task_result.task_id,
            "status": task_result.status,
            "name": task_result.name,
            # "backend":str(task_result.backend)
        }
    )

homework_09/sales_shop/shop/templates/shop/categories_with_products_tree.html
{% extends 'base.html' %}

{% block title %}
Categories tree
{% endblock %}

{% block body %}
<h1>Categories</h1>
<ul>
    {% for category in categories %}
    <li>
        {{category.name}}
        <ul>
            {% for product in category.products.all %}
            <li>
                <code>${{product.price}}</code>
                -
                {{product.name}}
            </li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
{% endblock %}

homework_09/sales_shop/shop/templates/shop/category_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Delete category {{category.name}}
{% endblock %}

{% block body %}
    <h1>Archived <code>{{category.name}}</code></h1>
    <div class="alert alert-danger">
        Are you sure want to archived category #{{category.pk}}
        with description <code>{{category.name}}</code>?
    </div>
    <form method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Archived">
    </form>
    <div>
    <a class="btn btn-info" href="{% url 'shop:category' pk=category.pk %}">Back
        to category details</a>
</div>
{% endblock %}

homework_09/sales_shop/shop/templates/shop/category_detail.html
{% extends 'base.html' %}

{% block title %}
Category {{category.name}}
{% endblock %}

{% block body %}
<h1>Category #{{category.pk}} details</h1>
<h2><code>{{category.name}}</code></h2>
<h3>Description:</h3>
<p> {{category.description}}</p>
<h3>Products:</h3>
{% for product in category.products.all %}
    <p>Name product: <code>{{ product.name }}</code> </p>
    <p>Description: <code>{{ product.description }}</code></p>
{% endfor %}
<div>
    <a class="btn btn-secondary"
        href="{% url 'shop:update-category' pk=category.pk %}">Update</a>
    {% if perms.shop.delete_category %}
    <a class="btn btn-warning"
        href="{% url 'shop:confirm-delete-category' pk=category.pk %}">Delete</a>
        {% endif %}
    <ul>
        <li>
            <a href="{% url 'shop:categories'%}">Back to categories</a>
        </li>
    </ul>
</div>
{% endblock %}

homework_09/sales_shop/shop/templates/shop/category_form.html
{% extends 'base.html' %}

{% block title %}
Create category
{% endblock title %}

{% block body %}
<h2>Create a new category</h2>
<form class="my-3" method="post">
    {% csrf_token %}
    <!-- {{form.as_p}} -->
    {% for field in form %}
    <p>
        <label class="form-label" for="{{field.auto_id}}">{{field.label}}</label>
        {{field}}</p>
    {% endfor %}
    <input class="btn btn-primary" type="submit" value="Create">
</form>
{% endblock %}

homework_09/sales_shop/shop/templates/shop/category_list.html
{% extends 'base.html' %}

{% block title %}
Categories
{% endblock title %}

{% block body %}
<h1>Categories</h1>
<div>
    <ul>
        {% for category in category_list %}
        <li>
            <a class="text-decoration-none"
                href="{% url 'shop:category' pk=category.pk %}">{{category.name}}</a>
        </li>
        {% endfor %}
    </ul>
</div>

<div>
    <ul>
        <li>
            <a href="{% url 'shop:create-category' %}">Create a new category</a>
        </li>
        <li>
            <a href="{% url 'shop:index' %}">Back to shop </a>
        </li>
    </ul>
</div>
{% endblock body %}

homework_09/sales_shop/shop/templates/shop/category_update_form.html
{% extends 'base.html' %}

{% block title %}
Update Category{{category.name}}
{% endblock title %}

{% block body %}
<h2> Update category # {{category.pk}} for name <code>{{category.name}}</code>
</h2>
<form class="my-3" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-primary" type="submit" value="Update">
</form>
<div>
    <a class="btn btn-info" href="{% url 'shop:category' pk=category.pk %}">Back
        to category details</a>
</div>
{% endblock %}

homework_09/sales_shop/shop/templates/shop/index.html
{% extends 'base.html' %}

{% block title %}
Shop index
{% endblock %}

{% block body %}
<div>
    <h1>
        Shop index
    </h1>
    <ul>
        <li>
            <a href="{% url 'shop:products'%}">Products</a>
        </li>        
        <li>
            <a href="{% url 'shop:orders'%}">Orders</a>
        </li>       
        <li>
            <a href="{% url 'shop:categories'%}">Categories</a>
        </li>       
        <li>
            <a href="{% url 'shop:categories_with_products_tree'%}">Categories with all products</a>
        </li>
    </ul>
</div>
{% endblock %}

homework_09/sales_shop/shop/templates/shop/orders.html
{% extends 'base.html' %}

{% block title %}
Orders
{% endblock title %}

{% block body %}
<h3>Orders</h3>
<ul>

    {% for order in orders %}
    <li>
        <p>
            #{{order.id}}
            <code>{{order.promocode}}</code>
        </p>
        <p>
            <strong>Adress:</strong>{{order.adress}}
        </p>
        <p>
            <strong>Ordered at :</strong>{{order.created_at}}
        </p>
        <ul>

            {% for product in order.products.all %}
            <li>
                #{{ product.pk }} {{ product.name }}
            </li>
            {% endfor %}
        </ul>
        <p><strong>Ordered by </strong>{{order.user}}</p>
        <p><strong>Card </strong>{{order.payment_details.card_ends_with}}</p>
    </li>
    {% endfor %}
</ul>
{% endblock body %}

homework_09/sales_shop/shop/templates/shop/products.html
{% extends 'base.html' %}

{% block title %}
Products
{% endblock title %}

{% block body %}
<h3>Products</h3>
<ul>
    {% for product in products %}
    <li>{{product.name}} -
        [{{product.category.name}}]
        <code>${{product.price}}</code>
    </li>
    {% endfor %}
</ul>
{% endblock body %}